version: 2
updates:
  # Go modules
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "deps(go)"
    labels:
      - "dependencies"
      - "go"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  # Docker images in /docker directory
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "deps(docker)"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "deps(actions)"
    labels:
      - "dependencies"
      - "github-actions"
      - "security-review"
    open-pull-requests-limit: 2
    groups:
      patch-only:
        update-types:
          - "patch"
