version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "divkix"
    assignees:
      - "divkix"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
