# golangci-lint configuration for Alita Robot
version: "2"

run:
  timeout: 5m

# Linters to enable
linters:
  enable:
    - godox      # Detects TODO, FIXME, and other keywords
    - dupl       # Detects duplicate code fragments
  # Linter settings (v2 format)
  settings:
    dupl:
      threshold: 100

# Output settings
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
