# golangci-lint configuration for Alita Robot
version: "2"

run:
  timeout: 5m

# Linters to enable
linters:
  enable:
    - godox      # Detects TODO, FIXME, and other keywords - requires issue references

# Linter settings
linters-settings:
  godox:
    # Keywords to detect
    keywords:
      - TODO
      - FIXME
      - HACK
      - XXX
    # Require issue reference in format: TODO(issue-ref), FIXME(issue-ref), etc.
    with-issue-ref: true
    issue-ref-format: "([a-zA-Z0-9._-]+)"  # Accepts issue numbers like #123, ISSUE-456, etc.

# Output settings
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
