version: "2"

run:
    go: "1.23"
    timeout: 5m
    tests: true
    modules-download-mode: readonly

linters:
    default: none
    enable:
        # Error detection
        - errcheck          # Check for unchecked errors
        - gosec             # Security audit
        - govet             # Standard Go vet checks
        - ineffassign       # Detect ineffectual assignments
        - staticcheck       # Advanced static analysis (includes gosimple, stylecheck)
        - typecheck         # Type checking errors
        - unused            # Find unused constants, variables, functions and types
        - bodyclose         # Check HTTP response body is closed
        - contextcheck      # Check context usage
        - errorlint         # Find code that will cause problems with Go error wrapping
        - nilerr            # Find code that returns nil even if it checks error
        
        # Code quality
        - gocyclo          # Cyclomatic complexity
        - goconst          # Find repeated strings that could be constants
        - gocritic         # Comprehensive linter with many checks
        - misspell         # Find commonly misspelled English words
        - unconvert        # Remove unnecessary type conversions
        - unparam          # Find unused function parameters
        - whitespace       # Tool for detection of leading and trailing whitespace
        
        # Style
        - revive           # Fast, configurable, extensible, flexible linter

    exclusions:
        generated: strict
        paths:
            - "vendor/"
            - ".*_test.go"
        rules:
            # Exclude some specific gosec rules in test files
            - path: "(.+)_test\\.go"
              linters:
                  - gosec
                  - gocyclo
                  - goconst
            # Exclude G404 (insecure random number source) in test files
            - path: "(.+)_test\\.go"
              text: "G404:"
              linters:
                  - gosec
            # Ignore security issues in sample/example files
            - path: "sample\\."
              linters:
                  - gosec
            # Ignore "Consider pre-allocating" for non-performance critical code
            - text: "Consider pre-allocating"
              linters:
                  - prealloc

    settings:
        gocyclo:
            min-complexity: 15
        
        goconst:
            min-len: 3
            min-occurrences: 3
        
        gocritic:
            enabled-tags:
                - diagnostic
                - style
                - performance
            disabled-checks:
                - dupImport # https://github.com/go-critic/go-critic/issues/845
                - ifElseChain
                - octalLiteral
                - whyNoLint
        
        revive:
            severity: warning
            rules:
                - name: exported
                  severity: warning
                  disabled: false
                  arguments:
                      - "checkPrivateReceivers"
                      - "sayRepetitiveInsteadOfStutters"
        
        staticcheck:
            checks:
                - "all"
                - "-SA1019" # Ignore deprecation warnings for now
        
        gosec:
            excludes:
                - G404 # Use of weak random number generator in tests is acceptable
            
        errcheck:
            check-type-assertions: true
            check-blank: true

formatters:
    enable:
        - gofmt            # Gofmt checks whether code was gofmt-ed
        - goimports        # Check import formatting
        - gci              # Control Go package import order
    
    settings:
        gci:
            sections:
                - standard
                - default
                - prefix(github.com/divideprojects/Alita_Robot)

output:
    formats:
        text:
            path: stdout