# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: alita_robot

release:
  replace_existing_draft: true
  header: |
    Welcome to this new release!

  footer: |
    Docker 🐳 images are available at:
    `docker pull ghcr.io/divkix/{{ .ProjectName }}:{{ .Tag }}`

gomod:
  env:
    - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - binary: alita_robot
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

archives:
  # - rlcp: true
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

dockers:
  - goarch: amd64
    dockerfile: docker/goreleaser
    use: buildx
    image_templates:
      - "ghcr.io/divkix/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - supabase
  - goarch: arm64
    dockerfile: docker/goreleaser
    use: buildx
    image_templates:
      - "ghcr.io/divkix/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - supabase

docker_manifests:
  - name_template: "ghcr.io/divkix/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/divkix/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/divkix/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
  - name_template: "ghcr.io/divkix/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/divkix/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/divkix/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
