name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  checks: read

jobs:
  check-dependabot:
    name: Check Dependabot PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    outputs:
      should-auto-merge: ${{ steps.check.outputs.should-auto-merge }}
      update-type: ${{ steps.dependabot-metadata.outputs.update-type }}
    steps:
      - name: Extract dependency information
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Check auto-merge eligibility
        id: check
        env:
          UPDATE_TYPE: ${{ steps.dependabot-metadata.outputs.update-type }}
        run: |
          echo "Update type: $UPDATE_TYPE"
          
          # Auto-merge minor and patch updates
          if [[ "$UPDATE_TYPE" == "version-update:semver-patch" ]] || [[ "$UPDATE_TYPE" == "version-update:semver-minor" ]]; then
            echo "should-auto-merge=true" >> $GITHUB_OUTPUT
            echo "✅ Auto-merge eligible: $UPDATE_TYPE"
          else
            echo "should-auto-merge=false" >> $GITHUB_OUTPUT
            echo "⚠️ Manual review required: $UPDATE_TYPE"
          fi


  auto-merge:
    name: Auto-merge Dependabot PR
    runs-on: ubuntu-latest
    needs: check-dependabot
    if: needs.check-dependabot.outputs.should-auto-merge == 'true'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "Enabling auto-merge for PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --auto --squash --delete-branch

  notify-major-update:
    name: Notify Major Update
    runs-on: ubuntu-latest
    needs: check-dependabot
    if: needs.check-dependabot.outputs.should-auto-merge == 'false'
    permissions:
      pull-requests: write
    steps:
      - name: Tag owner for major update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          UPDATE_TYPE: ${{ needs.check-dependabot.outputs.update-type }}
        run: |
          comment_body="@divkix Major version update detected!
          
          **Update type:** \`$UPDATE_TYPE\`
          
          This PR requires manual review for potential breaking changes."

          gh pr comment $PR_NUMBER --body "$comment_body"
