name: Lint

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

permissions:
    contents: read
    pull-requests: read
    checks: write

jobs:
    golangci:
        name: golangci-lint
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.23'
                  cache: false
                  
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  version: latest
                  args: --timeout=5m --config=.golangci.yml
                  only-new-issues: false
                  skip-cache: false
                  skip-save-cache: false